services:
  - type: web
    name: qr-file-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_AVsJD9Kg2Cej@ep-red-wind-adchaz2b-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
